<a href="https://colab.research.google.com/github/DatPhatCoder/git_test/blob/main/math_transpose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [8]:
 #using numpy to transpose vector

 #create a vector
 nv = np.array([[1,2,3,4]])
 print(nv), print('')

 #transpose it
print(nv.T), print('')

#transpose the transpose
nvT = nv.T
print(nvT.T)

[[1 2 3 4]]

[[1]
 [2]
 [3]
 [4]]

[[1 2 3 4]]


In [12]:
#using numpy to transpose matrix
nM = np.array([[1,2,3,4],
               [5,6,7,8]
               ])
print(nM), print('')

#tranpose it
print(nM.T), print('')

#tranpose the transpose
nMT = nM.T
print(nMT.T)

[[1 2 3 4]
 [5 6 7 8]]

[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
#using pytorch to tranpose a vector

#create a vector
tv = torch.tensor([[1,2,3,4]])
print(tv), print('')

#tranpose it
print(tv.T), print('')

#tranpose the tranpose
tvT = tv.T
print(tvT.T)

tensor([[1, 2, 3, 4]])

tensor([[1],
        [2],
        [3],
        [4]])

tensor([[1, 2, 3, 4]])


In [16]:
#using pytorch to tranpose a matrix

#create a matrix
tm = torch.tensor([[1,2,3,4],[5,6,7,8]])
print(tm), print('')

#tranpose it
print(tm.T), print('')

#tranpose the tranpose
tmT = tm.T
print(tmT.T)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [19]:
#examine data types
print(f'Variable nv is of type {type(nv)}')
print(f'Variable nv is of type {type(nM)}')
print(f'Variable nv is of type {type(tv)}')
print(f'Variable nv is of type {type(tm)}')

Variable nv is of type <class 'numpy.ndarray'>
Variable nv is of type <class 'numpy.ndarray'>
Variable nv is of type <class 'torch.Tensor'>
Variable nv is of type <class 'torch.Tensor'>
